const keywords = [
    "False",
    "None",
    "True",
    "and",
    "list",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "type",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "is",
    "end",
    "range",
    "lambda",
    "nonlocal",
    "not",
    ":",
    "list",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
    "print"
];

const operator_name_alpha = {
    'in': 'Membership (in)',
    'not in': 'Membership (not in)',
    'is': 'Identity (is)',
    'is not': 'Identity (is not)'
};

const operator_name_opr = {
    '=': 'Equals',
    '+': 'Addition',
    '-': 'Subtraction',
    '*': 'Multiplication',
    '/': 'Division',
    '%': 'Modulus',
    '**': 'Exponentilexical_stringation',
    '//': 'Floor Division',
    '<': 'Less Than',
    '>': 'Greater Than',
    '<=': 'Less Than or Equal To',
    '>=': 'Greater Than or Equal To',
    '==': 'Equal To',
    '!=': 'Not Equal To',
    '!==': 'Strict Not Equal To',
    '===': 'Strict Equal To',
    '&&': 'Logical AND',
    '||': 'Logical OR',
    '!': 'Logical NOT',
    '&': 'Bitwise AND',
    '|': 'Bitwise OR',
    '^': 'Bitwise XOR',
    '~': 'Bitwise NOT',
    '(': 'Left Parenthesis',
    ')': 'Right Parenthesis',
    '<<': 'Left Shift',
    '>>': 'Right Shift',
    '>>>': 'Unsigned Right Shift',
    ":": "Colon"
}
const in_built_methods = {
    'abs': 'Returns the absolute value of a number.',
    'len': 'Returns the number of items in an object.',
    'str': 'Converts an object into a string representation.',
    'int': 'Converts a number or string to an integer.',
    'float': 'Converts a number or string to a floating-point number.',
    'max': 'Returns the largest item in an iterable or the largest of two or more arguments.',
    'min': 'Returns the smallest item in an iterable or the smallest of two or more arguments.',
    'sum': 'Returns the sum of all items in an iterable.',
    'range': 'Generates a sequence of numbers.',
    'sorted': 'Returns a new sorted list from the items in an iterable.',
    'type': 'Returns the type of an object.',
    'list': 'Creates a list.',
    'dict': 'Creates a dictionary.',
    'tuple': 'Creates a tuple.',
    'set': 'Creates a set.',
    'zip': 'Returns an iterator that aggregates elements from multiple iterables.',
    'enumerate': 'Returns an iterator that yields pairs of an index and an element.',
    'map': 'Applies a function to all items in an input iterable.',
    'filter': 'Filters elements from an iterable based on a given function.',
    'reduce': 'Applies a function of two arguments cumulatively to the items of an iterable, from left to right, to reduce the iterable to a single value.'
  };
  
module.exports = {keywords, operator_name_alpha, operator_name_opr, in_built_methods}